### ISSUE TITLE
Hacktoberfest 2022

### ISSUE THREAD

**Issue by arthurits** [arthurits/SignalAnalysis#1]
# This repo is participating in Hacktoberfest 2022! #
Translations are welcome as a way to enter Hacktoberfest 2022.

## Contributions ##
 
We are looking for contributions to translate this project's string resources ([strings.resx](https://github.com/arthurits/SignalAnalysis/blob/master/SignalAnalysis/localization/strings.resx), 129 strings) into any of the [24 official languages in the EU](https://european-union.europa.eu/principles-countries-history/languages_en#:~:text=The%20EU%20has%2024%20official,%2C%20Slovenian%2C%20Spanish%20and%20Swedish.): 

- Bulgarian
- Croatian
- Czech
- ~~Danish~~
- Dutch (both ~~`nl-BE`~~ and `nl-NL`)
- ~~English~~
- Estonian
- Finnish
- French
- ~~German~~
- Greek
- Hungarian
- Irish
- ~~Italian~~
- Latvian
- ~~Lithuanian~~
- Maltese
- Polish
- Portuguese (both `pt-PT` ~~and `pt-BR`~~)
- Romanian
- Slovak
- Slovenian
- ~~Spanish~~
- Swedish

Other languages might be accepted (but not granted) upon personal consideration.

Please note that <kbd><img title="Bangla" alt="Bangla" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/bd.svg" width="22"></kbd>Bangla (bn-BD), <kbd><img title="Danish" alt="Danish" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/dk.svg" width="22"></kbd>Danish (da-DK), <kbd><img title="Dutch" alt="Dutch" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/be.svg" width="22"></kbd> Belgium Dutch (nl-BE), <kbd><img title="English" alt="English" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/gb.svg" width="22"></kbd>English, <kbd><img title="German" alt="German" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/de.svg" width="22"></kbd>German, <kbd><img title="Hindi" alt="Hindi" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/in.svg" width="22"></kbd> Hindi, <kbd><img title="Italian" alt="Italian" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/it.svg" width="22"></kbd>Italian, <kbd><img title="Lithuanian" alt="Lithuanian" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/lt.svg" width="22"></kbd>Lithuanian, <kbd><img title="Norwegian (Bokmål)" alt="Norwegian (Bokmål)" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/no.svg" width="22"></kbd>Norwegian (Bokmål), <kbd><img title="Portuguese (Brazil)" alt="Portuguese (Brazil)" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/br.svg" width="22"></kbd>Portuguese (pt-BR), <kbd><img title="Russian" alt="Russian" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/ru.svg" width="22"></kbd> Russian (ru-RU), <kbd><img title="Spanish" alt="Spanish" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/es.svg" width="22"></kbd>Spanish, and <kbd><img title="Turkish" alt="Turkish" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/tr.svg" width="22"></kbd>Turkish are already covered.

## Instructions ##
Create a new PR  by adding a new file in the [project's localization folder](https://github.com/arthurits/SignalAnalysis/tree/master/SignalAnalysis/localization) named `strings.xx-XX.resx`, where xx-XX stands for the chosen language; i.e.: `de-DE` for German, `fr-FR` for French, et cetera. The new file should contain all the string resources from the base [strings.resx](https://github.com/arthurits/SignalAnalysis/tree/master/SignalAnalysis/localization/strings.resx) translated into the chosen language.

Some of the string resources include string formatters and other characters (ampersands, line breaks, et cetera) that should be respected in order for the PR to be accepted.

## Approval ##
Please wait until your PR is reviewed, validated, merged and labelled with `hacktoberfest-accepted` before it is recognised in your [Hacktoberfest profile](https://hacktoberfest.com/).

**Comment by m1ga** [comment]
:de: file https://github.com/arthurits/SignalAnalysis/pull/2

**Comment by sarequl** [comment]
Can I translate this to Bangla (Bn)?

**Comment by sarequl** [comment]
Hi @arthurits 
Sure! I will keep same.

Thank You

**Comment by arthurits** [comment]
> Hi @arthurits Sure! I will keep same.
> 
> Thank You

Thanks @sarequl for your contribution!
Your PR #4 is already merged.

**Comment by Pyr0x1** [comment]
Hello, I can work on the italian translation if nobody is already doing it

**Comment by arthurits** [comment]
Hi @Pyr0x1!
I would be glad if you could.

**Comment by fadkeabhi** [comment]
I am done with hindi translations. and made a PR here arthurits/SignalAnalysis#6 . please approve with hacktoberfest-accepted label.

**Comment by lhardt** [comment]
I could work on adding the pt-BR translations

**Comment by arthurits** [comment]
> I could work on adding the pt-BR translations

That would be great! Whenever you are done, just create a new PR referencing this issue.
