### ISSUE TITLE
Arabic translation (Hacktoberfest 2022)

### ISSUE THREAD

**Issue by arthurits** [arthurits/SignalAnalysis#11]
# This repo is participating in Hacktoberfest 2022! #
We are looking for contributions to translate this project's string resources ([strings.resx](https://github.com/arthurits/SignalAnalysis/blob/master/SignalAnalysis/localization/strings.resx), 129 strings) into Arabic.
I'm not conversant with Arabic and its variants, so the options most widely used in software applications are preferred (maybe `ar-SA`).

## Instructions ##
Create a new PR by adding a new file in the [project's localization folder](https://github.com/arthurits/SignalAnalysis/blob/master/SignalAnalysis/localization) named `strings.xx-XX.resx` (where `xx-XX` stands for the Arabic variant chosen). The new file should contain all the string resources from the base [strings.resx](https://github.com/arthurits/SignalAnalysis/blob/master/SignalAnalysis/localization/strings.resx) translated into Arabic.

Some of the string resources include string formatters and other characters (ampersands, line breaks, et cetera) that should be respected in order for the PR to be accepted.

## Approval ##
Please wait until your PR is reviewed, validated, merged and labelled with `hacktoberfest-accepted` before it is recognised in your [Hacktoberfest profile](https://hacktoberfest.com/).

**Comment by mazen-r** [comment]
Hello, I can work on this issue. I will use AR-EG which is the most popular one.

**Comment by arthurits** [comment]
> Hello, I can work on this issue. I will use only plain Arabic with no variant.

Thanks for #12. Should you be interested, there's another Arabic translation needed [here](https://github.com/arthurits/ErgoLux/issues/11), where several of the the strings are identical to the ones you've already translated.

**Comment by arthurits** [comment]
PR #12 closes this issue.
Thanks @mazen-r for your contribution!
