### ISSUE TITLE
Translation needed

### ISSUE THREAD

**Issue by arthurits** [arthurits/SignalAnalysis#21]
Looking for help translating 33 localization strings. They are divided in three categories:
- MessageBox errors (title and description)
- Differentiation GUI settings
![image](https://user-images.githubusercontent.com/63915486/230590938-91081a9f-af03-4950-9f6b-e4ef6c8cc32d.png)
- Integration GUI settings
![image](https://user-images.githubusercontent.com/63915486/230591006-c32cb330-3f2c-45ff-ab16-2442bd4d6979.png)
- Differentiation plot
![image](https://user-images.githubusercontent.com/63915486/223777550-b3d77987-e9ba-4365-9efa-3aa93cb664ce.png)

## Languages and cultures ##

These are the languages the strings need to be translated:

* Arabic (ar). If possible, only plain Arabic with no variant
* Bangla (bn-BD) <kbd><img title="Bangla" alt="Bangla" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/bd.svg" width="22"></kbd>
* Danish (da-DK) <kbd><img title="Danish" alt="Danish" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/dk.svg" width="22"></kbd>
* Belgium Dutch (nl-BE) <kbd><img title="Dutch" alt="Dutch" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/be.svg" width="22"></kbd>
* German (de-DE) <kbd><img title="German" alt="German" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/de.svg" width="22"></kbd>
* Hindi (hi-IN) <kbd><img title="Hindi" alt="Hindi" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/in.svg" width="22"></kbd>
* Italian (it-IT) <kbd><img title="Italian" alt="Italian" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/it.svg" width="22"></kbd>
* Lithuanian (lt-LT) <kbd><img title="Lithuanian" alt="Lithuanian" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/lt.svg" width="22"></kbd>
* Norwegian (Bokmål) (nb-NO) <kbd><img title="Norwegian (Bokmål)" alt="Norwegian (Bokmål)" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/no.svg" width="22"></kbd>
* Portuguese (Brazil) (pt-BR) <kbd><img title="Portuguese (Brazil)" alt="Portuguese (Brazil)" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/br.svg" width="22"></kbd>
* Russian (ru-RU) <kbd><img title="Russian" alt="Russian" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/ru.svg" width="22"></kbd>
* Turkish (tr-TR) <kbd><img title="Turkish" alt="Turkish" src="https://cdn.staticaly.com/gh/hjnilsson/country-flags/master/svg/tr.svg" width="22"></kbd>

## Instructions ##

There are several ways to contribute the translations. However, all of them should be done via PR and one of the following three options:
- Edit this [Excel book](https://github.com/arthurits/SignalAnalysis/blob/master/SignalAnalysis/localization/PR%20translation.xlsx) and add the translated strings in the table.
- Copy the plain-text table below in the PR and add one more column with the translated strings.
- If you use VS along with the extension [ResX Manager](https://github.com/dotnet/ResXResourceManager) you can translate the strings without manually editing the resx file, since this extension automatically updates the corresponding `strings.xx-YY.resx` files.

| Key | Comment | English |
| -- | -- | -- |
| strChkAbsoluteIntegral | In "settings" form, tab   "Integration" | Compute the absolute-value integral? |
| strChkComputeDerivative | In   "settings" form | Compute numerical   differentiation? |
| strChkComputeIntegration | In "settings" form, tab   "Integration" | Compute numerical integration? |
| strChkExportDerivative | In   "settings" form | Export derivative   data? |
| strChkExportIntegration | In "settings" form, tab   "Integration" | Export numerical integration? |
| strDifferentiationAlgorithms | Algorithms to be   displayed as options in ComboBox | Backward   one-point difference, Forward one-point difference, Central three-point   difference, Central five-point difference, Central seven-point difference,   Central nine-point difference, Savitzky–Golay linear three point,   Savitzky–Golay linear five point, Savitzky–Golay linear seven point,   Savitzky–Golay linear nine point, Savitzky–Golay cubic five point,   Savitzky–Golay cubic seven point, Savitzky–Golay cubic nine point |
| strFileHeader28 | Column text header in exported files | Derivative |
| strFileHeader29 | Field description in   exported file | Differentiation   algorithm |
| strFileHeader30 | Column text header in exported files | Integration algorithm |
| strFileHeader31 | Column text header in   exported files | Integral value |
| strGrpAlgorithms | In "settings" form | Finite difference algorithms |
| strIntegrationAlgorithms | Algorithms to be   displayed as options in ComboBox | Left-point   rule, Mid-point rule, Right-point rule, Trapezoid rule, Simpson's 1/3 rule,   Simpson's 3/8 rule, Simpson's composite rule, Romberg's method |
| strLblIntegration | In "settings" form, tab   "Integration" | Quadrature algorithms |
| strMsgBoxErrorDerivative |   | Unexpected error   while computing numerical differentiation.     {0} |
| strMsgBoxErrorDerivativeTitle |   | Differentiation error |
| strMsgBoxErrorDescriptiveStats |   | Unexpected error   while computing descriptive statistics values.     {0} |
| strMsgBoxErrorDescriptiveStatsTitle |   | Statistics error |
| strMsgBoxErrorEntropy |   | Unexpected error   while computing entropy values.     {0} |
| strMsgBoxErrorEntropyTitle |   | Entropy error |
| strMsgBoxErrorFractal |   | Unexpected error   while computing the fractal dimension.     {0} |
| strMsgBoxErrorFractalTitle |   | Fractal error |
| strMsgBoxTaskDerivativeCancel |   | Numerical   differentiation has been stopped. |
| strMsgBoxTaskDerivativeCancelTitle |   | Cancel |
| strMsgBoxTaskEntropyCancel |   | Entropy computation   has been stopped. |
| strMsgBoxTaskEntropyCancelTitle |   | Cancel |
| strPlotDerivativeTitle | In plot derivative | Derivative |
| strPlotDerivativeXLabel | In plot derivative | Time (seconds) |
| strPlotDerivativeYLabel1 | In plot derivative.   Please take into account that "seconds" is abbreviated so that it   fits in the ordinate axis. | Amplitude / sec |
| strPlotDerivativeYLabel2 | In plot derivative | Amplitude |
| strStatusTipDerivative | Tooltip in the lower   right corner button | Numerical   differentiation |
| strStatusTipIntegration | Tooltip in the lower right corner button | Numerical integration |
| strTabDerivative | Tab text in   "settings" form | Differentiation |
| strTabIntegration | Tab text in "settings" form | Integration |

**Comment by xteaun** [comment]
Hey there! I would love to help out with German translations. :)

**Comment by shmudivel** [comment]
hello, @arthurits 

I want to help with additional translation.
I opened the strings.ru-RU.resx file, but could not find the keys you mentioned above, or I did something incorrectly. Could you please explain how to do it properly? 



> Looking for help translating 33 localization strings. They are divided in three categories:
> 
> * MessageBox errors (title and description)
> * Differentiation GUI settings
>   ![image](https://user-images.githubusercontent.com/63915486/230590938-91081a9f-af03-4950-9f6b-e4ef6c8cc32d.png)
> * Integration GUI settings
>   ![image](https://user-images.githubusercontent.com/63915486/230591006-c32cb330-3f2c-45ff-ab16-2442bd4d6979.png)
> * Differentiation plot
>   ![image](https://user-images.githubusercontent.com/63915486/223777550-b3d77987-e9ba-4365-9efa-3aa93cb664ce.png)
> 
> ## Languages and cultures
> These are the languages the strings need to be translated:
> 
> Arabic (ar). If possible, only plain Arabic with no variant Bangla (bn-BD) <img alt="Bangla" width="22" src="https://camo.githubusercontent.com/d96c24d563694cbbc4b88f8b18662d29d73b148c7336d72d25ef10368513f8d2/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f686a6e696c73736f6e2f636f756e7472792d666c6167732f6d61737465722f7376672f62642e737667"> Danish (da-DK) <img alt="Danish" width="22" src="https://camo.githubusercontent.com/a58d0e6c7610854930984426de2cfb6a8321f8081458c3184ab8b27c82397095/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f686a6e696c73736f6e2f636f756e7472792d666c6167732f6d61737465722f7376672f646b2e737667"> Belgium Dutch (nl-BE) <img alt="Dutch" width="22" src="https://camo.githubusercontent.com/2194770a8e109317a6cbce3c8d534016ba751995f79efcc689ddf2221b01b46e/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f686a6e696c73736f6e2f636f756e7472792d666c6167732f6d61737465722f7376672f62652e737667"> German (de-DE) <img alt="German" width="22" src="https://camo.githubusercontent.com/8d6d7cc6c232bddbdd753c9de78339452dc5ae069912e42ef302e2d01462a874/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f686a6e696c73736f6e2f636f756e7472792d666c6167732f6d61737465722f7376672f64652e737667"> Hindi (hi-IN) <img alt="Hindi" width="22" src="https://camo.githubusercontent.com/32664be6362a3b126c0c9fdc8a4fd3ce461ddd907cf0c13a88b02cf65934c8f2/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f686a6e696c73736f6e2f636f756e7472792d666c6167732f6d61737465722f7376672f696e2e737667"> Italian (it-IT) <img alt="Italian" width="22" src="https://camo.githubusercontent.com/287511a6400efa3221ad4a09af10c73c775385b362f44d45e95e679adacb475c/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f686a6e696c73736f6e2f636f756e7472792d666c6167732f6d61737465722f7376672f69742e737667"> Lithuanian (lt-LT) <img alt="Lithuanian" width="22" src="https://camo.githubusercontent.com/92f7d00231ec6744806d4d0df2b34711379cb1b778ad879fc6b2f990295771fe/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f686a6e696c73736f6e2f636f756e7472792d666c6167732f6d61737465722f7376672f6c742e737667"> Norwegian (Bokmål) (nb-NO) <img alt="Norwegian (Bokmål)" width="22" src="https://camo.githubusercontent.com/a91dccce61aa391b2a49b811b92e21664ea20653e7ec3153f708ac4049ec3c90/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f686a6e696c73736f6e2f636f756e7472792d666c6167732f6d61737465722f7376672f6e6f2e737667"> Portuguese (Brazil) (pt-BR) <img alt="Portuguese (Brazil)" width="22" src="https://camo.githubusercontent.com/dcc375ada213d3ac04a9781518098cd4d071601bc2ccfc120025cc32b6d38fab/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f686a6e696c73736f6e2f636f756e7472792d666c6167732f6d61737465722f7376672f62722e737667"> Russian (ru-RU) <img alt="Russian" width="22" src="https://camo.githubusercontent.com/4c820a968e4d8eb5ce2e93cb7a9463e4cf4e1dc164060296d4ce7dcf97ec503a/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f686a6e696c73736f6e2f636f756e7472792d666c6167732f6d61737465722f7376672f72752e737667"> Turkish (tr-TR) <img alt="Turkish" width="22" src="https://camo.githubusercontent.com/56e02c175ca990aff11fd1b5e3520cccd6a0446531f0268050be840bea918dd6/68747470733a2f2f63646e2e737461746963616c792e636f6d2f67682f686a6e696c73736f6e2f636f756e7472792d666c6167732f6d61737465722f7376672f74722e737667">
> 
> ## Instructions
> There are several ways to contribute the translations. However, all of them should be done via PR and one of the following three options:
> 
> * Edit this [Excel book](https://github.com/arthurits/SignalAnalysis/blob/master/SignalAnalysis/localization/PR%20translation.xlsx) and add the translated strings in the table.
> * Copy the plain-text table below in the PR and add one more column with the translated strings.
> * If you use VS along with the extension [ResX Manager](https://github.com/dotnet/ResXResourceManager) you can translate the strings without manually editing the resx file, since the this extension automatically updates the corresponding `strings.xx-YY.resx` files.
> 
> Key	Comment	English
> strChkAbsoluteIntegral	In "settings" form, tab "Integration"	Compute the absolute-value integral?
> strChkComputeDerivative	In "settings" form	Compute numerical differentiation?
> strChkComputeIntegration	In "settings" form, tab "Integration"	Compute numerical integration?
> strChkExportDerivative	In "settings" form	Export derivative data?
> strChkExportIntegration	In "settings" form, tab "Integration"	Export numerical integration?
> strDifferentiationAlgorithms	Algorithms to be displayed as options in ComboBox	Backward one-point difference, Forward one-point difference, Central three-point difference, Central five-point difference, Central seven-point difference, Central nine-point difference, Savitzky–Golay linear three point, Savitzky–Golay linear five point, Savitzky–Golay linear seven point, Savitzky–Golay linear nine point, Savitzky–Golay cubic five point, Savitzky–Golay cubic seven point, Savitzky–Golay cubic nine point
> strFileHeader28	Column text header in exported files	Derivative
> strFileHeader29	Field description in exported file	Differentiation algorithm
> strFileHeader30	Column text header in exported files	Integration algorithm
> strFileHeader31	Column text header in exported files	Integral value
> strGrpAlgorithms	In "settings" form	Finite difference algorithms
> strIntegrationAlgorithms	Algorithms to be displayed as options in ComboBox	Left-point rule, Mid-point rule, Right-point rule, Trapezoid rule, Simpson's 1/3 rule, Simpson's 3/8 rule, Simpson's composite rule, Romberg's method
> strLblIntegration	In "settings" form, tab "Integration"	Quadrature algorithms
> strMsgBoxErrorDerivative	 	Unexpected error while computing numerical differentiation. {0}
> strMsgBoxErrorDerivativeTitle	 	Differentiation error
> strMsgBoxErrorDescriptiveStats	 	Unexpected error while computing descriptive statistics values. {0}
> strMsgBoxErrorDescriptiveStatsTitle	 	Statistics error
> strMsgBoxErrorEntropy	 	Unexpected error while computing entropy values. {0}
> strMsgBoxErrorEntropyTitle	 	Entropy error
> strMsgBoxErrorFractal	 	Unexpected error while computing the fractal dimension. {0}
> strMsgBoxErrorFractalTitle	 	Fractal error
> strMsgBoxTaskDerivativeCancel	 	Numerical differentiation has been stopped.
> strMsgBoxTaskDerivativeCancelTitle	 	Cancel
> strMsgBoxTaskEntropyCancel	 	Entropy computation has been stopped.
> strMsgBoxTaskEntropyCancelTitle	 	Cancel
> strPlotDerivativeTitle	In plot derivative	Derivative
> strPlotDerivativeXLabel	In plot derivative	Time (seconds)
> strPlotDerivativeYLabel1	In plot derivative. Please take into account that "seconds" is abbreviated so that it fits in the ordinate axis.	Amplitude / sec
> strPlotDerivativeYLabel2	In plot derivative	Amplitude
> strStatusTipDerivative	Tooltip in the lower right corner button	Numerical differentiation
> strStatusTipIntegration	Tooltip in the lower right corner button	Numerical integration
> strTabDerivative	Tab text in "settings" form	Differentiation
> strTabIntegration	Tab text in "settings" form	Integration

**Comment by shmudivel** [comment]
hello, @arthurits 

I want to help with additional translation.
I opened the strings.ru-RU.resx file, but could not find the keys you mentioned above, or I did something incorrectly. Could you please explain how to do it properly?

**Comment by arthurits** [comment]
Hi @shmudivel!

Thanks for your interest. You are absolutely right: file `strings.ru-RU.resx` is missing some of the keys needing translation. I've just updated the file by adding the missing keys and the Englisht text at the very bottom, so they can be easily located.

By the way, some days ago I translated some entries (`strTabDerivative`, `strTabIntegration`, `strPlotDerivativeYLabel1`, `strPlotDerivativeYLabel2`, and `strFileHeader28`). I'd love if you wouldn't mind having a look at them and any other string that could be improved. I'll gladly provide context and screenshots whenever needed.

**Comment by shmudivel** [comment]
hi @arthurits 
I am having trouble understanding "strIntegrationAlgorithms" - "Left-point rule, Mid-point rule, Right-point rule"

could you give screenshots or more explanation about it? 
is there a difference between "Left Endpoint, Right Endpoint, and Midpoint Rules"?
thanks

**Comment by shmudivel** [comment]
also if possible screenshots for "strFileHeader33", "strFileHeader34", "strDifferentiationAlgorithms".
thank you
