### ISSUE TITLE
Unrecognized character in GBK encoding

### ISSUE THREAD

**Issue by myd7349** [arthurits/SignalAnalysis#28]
Hi!
It seems that `FrmMain.cs` has an ANSI encoding, as a result, some characters can not be recognized in other encodings(CP936, for example).
![图片](https://user-images.githubusercontent.com/5435649/225343933-de053165-9abb-421a-9db1-36a50e83d969.png)

![图片](https://user-images.githubusercontent.com/5435649/225344364-02dbd0e3-6ed8-4807-8734-cda5dcbdfd16.png)

Solution:

Save `FrmMain.cs` with UTF-8-BOM or UTF-8 encoding.

**Comment by arthurits** [comment]
Hi @myd7349:

Good catch! You are absolutely right,
As per your suggestions, the encoding has been changed to UTF-8 BOM in the following commit: https://github.com/arthurits/SignalAnalysis/commit/a0a3fb7a1b78cca689244ce09128f59c258914af 

Thank you!

**Comment by myd7349** [comment]
Confirm fixed.
