### ISSUE TITLE
Chinese translation (Hacktoberfest 2022)

### ISSUE THREAD

**Issue by arthurits** [arthurits/SignalAnalysis#8]
# This repo is participating in Hacktoberfest 2022! #
We are looking for contributions to translate this project's string resources ([strings.resx](https://github.com/arthurits/SignalAnalysis/blob/master/SignalAnalysis/localization/strings.resx), 129 strings) into Chinese.
I'm not conversant with Chinese and its variants, so the most widely used in software applications are preferred (these might be `zh-CN`, `zh-Hant`, `zh-Hans`).

## Instructions ##
Create a new PR by adding a new file in the [project's localization folder](https://github.com/arthurits/SignalAnalysis/blob/master/SignalAnalysis/localization) named `strings.xx-XX.resx` (where `xx-XX` stands for the Chinese variant chosen). The new file should contain all the string resources from the base [strings.resx](https://github.com/arthurits/SignalAnalysis/blob/master/SignalAnalysis/localization/strings.resx) translated into Chinese.

Some of the string resources include string formatters and other characters (ampersands, line breaks, et cetera) that should be respected in order for the PR to be accepted.

### Approval ###
Please wait until your PR is reviewed, validated, merged and labelled with `hacktoberfest-accepted` before it is recognised in your [Hacktoberfest profile](https://hacktoberfest.com/).

**Comment by myd7349** [comment]
Hello! @arthurits I am working on the Simplified Chinese translation right now.
https://github.com/myd7349/SignalAnalysis/tree/add-zh-Hans-translation

I will create a PR once I finish this in this week.

**Comment by arthurits** [comment]
Hi @myd7349,
That would be great! No need to hurry.
Please let me know if you prefer to work with the strings in a table format (Excel), instead of working with the resx file, or any other way that makes your task easier.
If you are using VS, the extension ResX Manager will make your life easier working with resx and string resources.

**Comment by myd7349** [comment]
Hello. @arthurits I have used ResXManager before, so I can do this using ResXManager.

**Comment by myd7349** [comment]
Hi! @arthurits I just created a PR to add zh-Hans translation.

**Comment by arthurits** [comment]
Hi @myd7349!

I really appreciate your hard work and your comments in #27.
Thank you very much for translating the plot context menu strings as well, especially since I forgot to mention it in this issue.

All in all thanks for taking your time to have a look beyond the mere string file to be translated and making suggestions.

I've just added a recent string as part of the settings. Here's a screenshot:
![image](https://user-images.githubusercontent.com/63915486/225552673-55bccbb6-aa1f-4e6b-ba51-03253ee60346.png)

Using an automatic translator, the suggested Simplified Chinese equivalent is: `计算绝对值积分？`. I'd love to hearing your opinion. Or, if you prefer, you can create a PR including the correct translation.

I wouldn't like to be a pest and upset you, but on a related note, I'm looking for another Chinese translation [here](https://github.com/arthurits/ErgoLux/issues/8). It requieres a bit more work (186 strings) but many strings are identical to the ones here. Should you be interested, please let me know.

**Comment by myd7349** [comment]
Hi! @arthurits Thank you for your kind words. I am glad to help doing this.

> Using an automatic translator, the suggested Simplified Chinese equivalent is: 计算绝对值积分？. I'd love to hearing your opinion.

I think `计算绝对值积分？`  is an appropriate translation.

> I wouldn't like to be a pest and upset you, but on a related note, I'm looking for another Chinese translation https://github.com/arthurits/ErgoLux/issues/8. It requieres a bit more work (186 strings) but many strings are identical to the ones here. Should you be interested, please let me know.

Yes. I am interested. I will start this from this Sunday. However, I must admit that I am not quite familiar with `ErgoLux` currently. I will take some time to learn about its usage to ensure that my translation is as accurate as possible.

**Comment by arthurits** [comment]
> I think `计算绝对值积分？` is an appropriate translation.

Nice, I'll add it to the resources file.

> Yes. I am interested. I will start this from this Sunday. However, I must admit that I am not quite familiar with `ErgoLux` currently. I will take some time to learn about its usage to ensure that my translation is as accurate as possible.

Thanks so much! There's no need to hurry, so please take your time. Should there be any questions, please don't hesitate to let me know.
